import './globals.css';

import type { Metadata } from 'next';
import { Noto_Serif } from 'next/font/google';
import { cn } from '@/utils/cn';
import { BaseProviders } from './providers';

const notoSerif = Noto_Serif({ subsets: ['latin'], variable: '--noto-serif' });

export const metadata: Metadata = {
  title: 'read-a-book',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body suppressHydrationWarning className={cn(notoSerif.variable)}>
        <BaseProviders>{children}</BaseProviders>
      </body>
    </html>
  );
}
